#pragma once

#include <iostream>
#include <vector>	
#include <unordered_map>
#include <chrono>
#include <random>
#include "imgui.h"
#include "imgui_impl_win32.h"
#include "imgui_impl_dx11.h"
#include <d3d11.h>
#include <tchar.h>
#include <Windows.h>
#include <functional>
#include <stdlib.h>
#include <crtdbg.h>
#include <sstream>
#include <unordered_set>
#include "Macro.h"
#include "Singleton.h"
#include "define.h"